services:
  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: 'guide-rabbit'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
#      - '5672'
